# Generated by Django 3.1.4 on 2021-03-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('pub_date', models.DateField()),
                ('recurring', models.BooleanField()),
                ('event_date', models.DateField()),
            ],
        ),
    ]
